# Generated by Django 4.1.3 on 2022-11-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название монеты')),
                ('desription', models.CharField(max_length=250, verbose_name='Описание монеты')),
                ('capitalization', models.IntegerField(verbose_name='Капитализация монеты')),
                ('cost', models.IntegerField(verbose_name='Стоимость 1 монеты')),
                ('date', models.DateTimeField(verbose_name='Время последнего лобновления')),
            ],
        ),
    ]
