# Generated by Django 4.1.3 on 2022-12-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coins',
            options={'verbose_name': 'Монета', 'verbose_name_plural': 'Монеты'},
        ),
        migrations.AlterField(
            model_name='coins',
            name='cost',
            field=models.FloatField(verbose_name='Стоимость 1 монеты'),
        ),
        migrations.AlterField(
            model_name='coins',
            name='date',
            field=models.DateTimeField(verbose_name='Время последнего обновления'),
        ),
        migrations.AlterField(
            model_name='coins',
            name='description',
            field=models.TextField(verbose_name='Описание монеты'),
        ),
    ]
